import os

STRADDLE = True
STITCH_STRADDLE_DATA = True
GRAPH_NORMALIZATION = False

# # BACKTEST_AVERAGE_BASIS_POINTS = [0]
# BACKTEST_AVERAGE_BASIS_POINTS = [0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
BACKTEST_AVERAGE_BASIS_POINTS = [0, 10.0, 20.0, 30.0, 40.0, 50.0]

GRAPH_THRESHOLD = 0.45
PEARSON = True

OUTPUT_FOLDER = lambda lbw: os.path.join("data", f"gml_{(lbw if lbw else 'none')}lbw")

# CPD_QUANDL_OUTPUT_FOLDER_DEFAULT = OUTPUT_FOLDER(CPD_DEFAULT_LBW)

FEATURES_FILE_PATH = lambda lbw: os.path.join(
    "data", f"gml_{(lbw if lbw else 'none')}lbw.csv"
)

# FEATURES_STRADDLES_FILE_PATH = FEATURES_FILE_PATH(21)
FEATURES_STRADDLES_FILE_PATH = os.path.join("data", "straddle_features", "features.csv")
FEATURES_EQUITIES_FILE_PATH = os.path.join("data", "equity_features", "features.csv")

ALL_TICKERS = [
    "AAPL", # 0
    "ABT",
    "ACN",
    "ADBE",
    "AIG",
    "AMGN",
    "AMT",
    "AMZN",
    "AVGO",
    "AXP",
    "BAC", # 10
    "BA",
    "BKNG",
    "BK",
    "BLK",
    "BMY",
    "BRKB",
    "CAT",
    "CL",
    "CMCSA",
    "COF", # 20
    "COP",
    "COST",
    "CRM",
    "CSCO",
    "CVS",
    "CVX",
    "C",
    "DE",
    "DHR",
    "DIS", # 30
    # "DUK",
    "EMR",
    "FDX",
    "F",
    "GD",
    "GE",
    "GILD",
    "GOOGL",
    "GS",
    "HD",
    "HON",
    "IBM",
    "INTC",
    "INTU",
    "JNJ",
    "JPM",
    "KO",
    # "LIN",
    "LLY",
    "LMT",
    "LOW",
    "MA",
    "MCD",
    "MDLZ",
    "MDT",
    "MET",
    "MMM",
    "MO",
    "MRK",
    "MSFT",
    "MS",
    "NEE",
    "NFLX",
    "NKE",
    "NVDA",
    "ORCL",
    "PEP",
    "PFE",
    "PG",
    "PM",
    "QCOM",
    "RTX",
    "SBUX",
    "SO",
    "SPG",
    "TGT",
    "TMO",
    "TMUS",
    # "TSLA",
    "TXN",
    "T",
    "UNH",
    "UNP",
    "UPS",
    "USB",
    "VZ",
    "V",
    "WFC",
    "WMT",
    "XOM",
]

# ALL_TICKERS = [
#     "AAPL",
#                "ABT",
#                ]

# ALL_TICKERS = [
#     "AAPL", # 0
#     "ABT",
#     "ACN",
#     "ADBE",
#     "AIG",
#     "AMGN",
#     "AMT",
#     "AMZN",
#     "AVGO",
#     "AXP",
#     "BAC",
# ]

BBG_SECTORS = {
    "AAPL": "Information Technology",
    "ABT": "Healthcare",
    "ACN": "Information Technology",
    "ADBE": "Information Technology",
    "AIG": "Financials",
    "AMGN": "Healthcare",
    "AMT": "Real Estate",
    "AMZN": "Consumer Discretionary",
    "AVGO": "Information Technology",
    "AXP": "Financials",
    "BAC": "Financials",
    "BA": "Industrials",
    "BKNG": "Consumer Discretionary",
    "BK": "Financials",
    "BLK": "Financials",
    "BMY": "Healthcare",
    "BRKB": "Financials",
    "CAT": "Industrials",
    "CL": "Consumer Staples",
    "CMCSA": "Communication Services",
    "COF": "Financials",
    "COP": "Energy",
    "COST": "Consumer Staples",
    "CRM": "Information Technology",
    "CSCO": "Information Technology",
    "CVS": "Healthcare",
    "CVX": "Energy",
    "C": "Financials",
    "DE": "Industrials",
    "DHR": "Healthcare",
    "DIS": "Communication Services",
    "EMR": "Industrials",
    "FDX": "Industrials",
    "F": "Consumer Discretionary",
    "GD": "Industrials",
    "GE": "Industrials",
    "GILD": "Healthcare",
    "GOOGL": "Communication Services",
    "GS": "Financials",
    "HD": "Consumer Discretionary",
    "HON": "Industrials",
    "IBM": "Information Technology",
    "INTC": "Information Technology",
    "INTU": "Information Technology",
    "JNJ": "Healthcare",
    "JPM": "Financials",
    "KO": "Consumer Staples",
    "LLY": "Healthcare",
    "LMT": "Industrials",
    "LOW": "Consumer Discretionary",
    "MA": "Financials",
    "MCD": "Consumer Discretionary",
    "MDLZ": "Consumer Staples",
    "MDT": "Healthcare",
    "MET": "Financials",
    "MMM": "Industrials",
    "MO": "Consumer Staples",
    "MRK": "Healthcare",
    "MSFT": "Information Technology",
    "MS": "Financials",
    "NEE": "Utilities",
    "NFLX": "Communication Services",
    "NKE": "Consumer Discretionary",
    "NVDA": "Information Technology",
    "ORCL": "Information Technology",
    "PEP": "Consumer Staples",
    "PFE": "Healthcare",
    "PG": "Consumer Staples",
    "PM": "Consumer Staples",
    "QCOM": "Information Technology",
    "RTX": "Industrials",
    "SBUX": "Consumer Discretionary",
    "SO": "Utilities",
    "SPG": "Real Estate",
    "TGT": "Consumer Discretionary",
    "TMO": "Healthcare",
    "TMUS": "Communication Services",
    "TXN": "Information Technology",
    "T": "Communication Services",
    "UNH": "Healthcare",
    "UNP": "Industrials",
    "UPS": "Industrials",
    "USB": "Financials",
    "VZ": "Communication Services",
    "V": "Financials",
    "WFC": "Financials",
    "WMT": "Consumer Staples",
    "XOM": "Energy",
}
